import Head from 'next/head'
import About from '../components/About'
import Contact from '../components/Contact'
import Main from '../components/Main'
import Nav from '../components/Nav'
import Portfolio from '../components/Portfolio'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Enzo Gabriel Holgado</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-gray-100 scroll-smooth w-screen ' >
        <Nav />
        <Main />
        <About />
        <Portfolio />
        <Contact />
      </main>
    </div>
  )
}
